// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.packtpub.springsecurity.events.client.managed.ui;

import com.google.gwt.text.shared.AbstractRenderer;
import com.packtpub.springsecurity.events.client.managed.request.ApplicationEntityTypesProcessor;
import com.packtpub.springsecurity.events.client.proxy.EventProxy;
import com.packtpub.springsecurity.events.client.scaffold.place.ProxyListPlace;

public abstract class ApplicationListPlaceRenderer_Roo_Gwt extends AbstractRenderer<ProxyListPlace> {

    public String render(ProxyListPlace object) {
        return new ApplicationEntityTypesProcessor<String>() {

            @Override
            public void handleEvent(EventProxy isNull) {
                setResult("Events");
            }
        }.process(object.getProxyClass());
    }
}
