// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.packtpub.springsecurity.events.client.managed.activity;

import com.google.gwt.place.shared.Place;
import com.google.gwt.place.shared.PlaceController;
import com.google.gwt.view.client.Range;
import com.google.web.bindery.requestfactory.shared.Receiver;
import com.google.web.bindery.requestfactory.shared.Request;
import com.packtpub.springsecurity.events.client.managed.request.ApplicationRequestFactory;
import com.packtpub.springsecurity.events.client.proxy.EventProxy;
import com.packtpub.springsecurity.events.client.scaffold.ScaffoldMobileApp;
import com.packtpub.springsecurity.events.client.scaffold.activity.IsScaffoldMobileActivity;
import com.packtpub.springsecurity.events.client.scaffold.place.AbstractProxyListActivity;
import com.packtpub.springsecurity.events.client.scaffold.place.ProxyListView;
import java.util.List;

public abstract class EventListActivity_Roo_Gwt extends AbstractProxyListActivity<EventProxy> implements IsScaffoldMobileActivity {

    protected ApplicationRequestFactory requests;

    public EventListActivity_Roo_Gwt(PlaceController placeController, ProxyListView<com.packtpub.springsecurity.events.client.proxy.EventProxy> view, Class<com.packtpub.springsecurity.events.client.proxy.EventProxy> proxyType) {
        super(placeController, view, proxyType);
    }

    protected void fireCountRequest(Receiver<java.lang.Long> callback) {
        requests.eventRequest().countEvents().fire(callback);
    }
}
