// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.packtpub.springsecurity.events.server.domain;

import com.packtpub.springsecurity.events.server.domain.EventDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect EventDataOnDemand_Roo_Configurable {
    
    declare @type: EventDataOnDemand: @Configurable;
    
}
